#!/usr/bin/env bash

set -e

DIR=$( dirname "${BASH_SOURCE[0]}" )
cd $DIR
DIR=`pwd`

BUILD=$DIR/lg_builder/scripts/lg-ros-build
DEBDIR=$DIR/catkin/debs

rm -rf $DEBDIR
mkdir -p $DEBDIR
cd $DEBDIR

sudo rosdep init
rosdep update
rosdep install --from-paths $DIR --ignore-src \
    --rosdistro=indigo --os=ubuntu:trusty \
    --skip-keys="appctl interactivespaces_msgs"

$BUILD $DIR/lg_common
sudo dpkg -i ros-indigo-lg-common_*.deb
$BUILD $DIR/lg_builder
$BUILD $DIR/lg_earth
$BUILD $DIR/lg_media
$BUILD $DIR/lg_nav_to_device
$BUILD $DIR/lg_sv
$BUILD $DIR/liquidgalaxy

