#!/usr/bin/env bash

set -e

DIR=$( dirname "${BASH_SOURCE[0]}" )
cd $DIR
DIR=`pwd`

BUILD=$DIR/lg_builder/scripts/lg-ros-build
SRCDIR=$DIR/catkin/src
DEBDIR=$DIR/catkin/debs

rm -rf $DEBDIR
mkdir -p $DEBDIR
cd $DEBDIR

sudo rosdep init || /bin/true
rosdep update
sudo rosdep install -y --from-paths $SRCDIR --ignore-src \
    --rosdistro=indigo --os=ubuntu:trusty

if [ -e $SRCDIR/appctl ]; then
    $BUILD $SRCDIR/appctl
    sudo dpkg --force-overwrite -i ros-indigo-appctl_*.deb
fi
$BUILD $SRCDIR/interactivespaces_msgs
sudo dpkg --force-overwrite -i ros-indigo-interactivespaces-msgs_*.deb
$BUILD $SRCDIR/lg_common
sudo dpkg -i ros-indigo-lg-common_*.deb
$BUILD $SRCDIR/lg_activity
$BUILD $SRCDIR/lg_attract_loop
$BUILD $SRCDIR/lg_builder
$BUILD $SRCDIR/lg_earth
$BUILD $SRCDIR/lg_json_config
$BUILD $SRCDIR/lg_keyboard
$BUILD $SRCDIR/lg_media
$BUILD $SRCDIR/lg_mirror
$BUILD $SRCDIR/lg_nav_to_device
$BUILD $SRCDIR/lg_offliner
$BUILD $SRCDIR/lg_panovideo
$BUILD $SRCDIR/lg_proximity
$BUILD $SRCDIR/lg_replay
$BUILD $SRCDIR/lg_rfreceiver
$BUILD $SRCDIR/lg_spacenav_globe
$BUILD $SRCDIR/lg_stats
$BUILD $SRCDIR/lg_sv
$BUILD $SRCDIR/lg_twister
$BUILD $SRCDIR/lg_pointer
$BUILD $SRCDIR/lg_wireless_devices
$BUILD $SRCDIR/lg_screenshot
$BUILD $SRCDIR/spacenav_wrapper
$BUILD $SRCDIR/state_proxy
$BUILD $SRCDIR/rfid_scanner
$BUILD $SRCDIR/rfreceiver
$BUILD $SRCDIR/wiimote
$BUILD $SRCDIR/lg_volume_control
$BUILD $SRCDIR/liquidgalaxy
