#!/usr/bin/env python

import os
import argparse
from subprocess import Popen
from ConfigParser import RawConfigParser, NoSectionError, NoOptionError

# make sure to set the root directory
ROOT_DIR = os.path.realpath(os.curdir)
ARGS = None
# add more directories here as needed
IGNORE_DIRS = ['catkin', 'scripts', '.git', 'tmp', '.idea']
NEEDED_DIRS = ['appctl']

if os.path.basename(ROOT_DIR) == 'scripts':
    os.chdir('..')
    ROOT_DIR = os.path.realpath(os.curdir)
if not os.path.isdir('.git'):
    raise Exception('Must run this script from the lg_ros_nodes project root'
            ' directory or inside the scripts dir')


def get_option(config, section, option):
    opt = None
    try:
        opt = config.get(section, option)
    except NoSectionError:
        pass
    except NoOptionError:
        pass
    return opt


def parse_config():
    """
    Sets globals which are better set in a config file
    """
    config_file = 'scripts/init.cfg'
    if not os.path.exists(config_file):
        print 'WARNING, no %s found, using possibly outdated configuration' % config_file
        return  # rely on hard coded values... maybe an exception would work
    # setting these globals
    global IGNORE_DIRS
    global NEEDED_DIRS

    config = RawConfigParser()
    config.read(config_file)
    section = 'init_workspace'
    needed = get_option(config, section, 'needed_dirs')
    if needed:
        NEEDED_DIRS = [need.strip() for need in needed.split(',')]
    ignores = get_option(config, section, 'ignore_dirs')
    if ignores:
        IGNORE_DIRS = [ignore.strip() for ignore in ignores.split(',')]


def setup_catkin():
    """
    Sets up the catkin dir structure, then creates all links
    """
    make_catkin_dir_structure()
    create_links_in_catkin()
    catkin_init()


def make_catkin_dir_structure():
    """
    creates catkin and catkin/src folders
    """
    check_exists_but_not_dir(ROOT_DIR + '/catkin')
    check_exists_but_not_dir(ROOT_DIR + '/catkin/src')


def check_exists_but_not_dir(location):
    """
    Checks if the location exists, then tries to make a directory there
    Will raise an error if a non-directory thing is there
    """
    if os.path.exists(location) and not os.path.isdir(location):
        raise Exception('%s exists but is not a directory' % location)
    mkdir(location)


def mkdir(location):
    """
    Makes a directory as long as one doesn't exist
    """
    if not os.path.exists(location):
        os.mkdir(location)


def create_links_in_catkin():
    """
    Creates all links from all the ros nodes in the root_dir + any passed as arguments
    """
    ros_nodes = get_ros_nodes()
    os.chdir("%s/catkin/src" % ROOT_DIR)
    create_links(ros_nodes)


def get_ros_nodes():
    """
    Figures out which directories in root_dir + ARGS exist
    returns an array of them
    """
    nodes = [
        '%s/%s' % (ROOT_DIR, d) for d in os.listdir(ROOT_DIR)
        if os.path.isdir('%s/%s' % (ROOT_DIR, d)) and d not in IGNORE_DIRS
    ]
    global ARGS
    # append any args with paths that exist to our nodes
    append_node(nodes, ARGS.appctl)
    for arg in ARGS.extra:
        append_node(nodes, arg)
    return nodes


def append_node(nodes, node):
    if not node:
        return
    node = os.path.expanduser(node)
    if not os.path.exists(node):
        return
    while node[-1] == '/':
        node = node[:-1]
    nodes.append(node)


def create_links(nodes):
    """
    Iterates over all nodes to be created, and has a link created for each
    """
    for node in nodes:
        create_link(node)


def create_link(node):
    """
    Creates a link to node named os.path.basename(node) if nothing exists there
    """
    path = os.path.basename(node)
    if os.path.exists(path):
        return
    # a dead link doesn't "exist," but it is still a link, remove it
    if os.path.islink(path):
        os.unlink(path)
    os.symlink(node, path)


def catkin_init():
    """
    Runs catkin_init_workspace in root_dir/catkin/src folder
    """
    os.chdir("%s/catkin/src" % ROOT_DIR)
    # No need to init workspace if this already exists
    if os.path.exists('CMakeLists.txt'):
        return
    try:
        p = None
        with open('/dev/null') as out:
            p = Popen("catkin_init_workspace", stdout=out, stderr=out)
        p.wait()
        if p.returncode != 0:
            raise Exception("catkin_init_workspace exited with a code of %d" % p.return_code)
    except OSError:
        raise Exception("Error running catkin_init_workspace, is it not in your PATH?")


def parse_args():
    """
    Simple argument parser
    """
    parser = argparse.ArgumentParser(
            description='initializes a the catkin workspace for this project')
    parser.add_argument('-a', '--appctl', type=str, help='location of appctl directory')
    parser.add_argument('-x', '--extra', type=str, nargs='*', default=[],
            help='a list of any extra paths to ros nodes you want linked to')
    return parser.parse_args()

def check_validity():
    """
    Just checks to see if appctl and interactivespaces_msgs exist in catkin/src
    """
    passed = True
    links = os.listdir("%s/catkin/src" % ROOT_DIR)
    for needed in NEEDED_DIRS:
        if needed not in links:
            passed = False
            print "############## WARNING catkin/src SHOULD HAVE %s LINK ##############" % needed
    if passed:
        print "Successfully completed workspace initialization"


def main():
    global ARGS
    parse_config()
    ARGS = parse_args()
    setup_catkin()
    check_validity()

if __name__ == '__main__':
    main()
