#!/usr/bin/env python3
"""Run the offline (nosetest) suite inside the lg_ros_nonfree container.

Not meant to be run by hand -- scripts/test_local.sh starts the container and
the throwaway MQTT broker this needs, then invokes this script inside it.

Why this exists: the display image is not raw ROS. Its install space is
transpiled to the visionport `vpros` shim, so a checkout cannot be tested with
rostest/nosetests without a full ROS toolchain (which the headnode does not
have). This stages the working tree the way the image build does -- flattening
`<pkg>/src/<pkg>/` to `<pkg>/` and transpiling every module with the
authoritative transpiler -- then runs the tests registered in the CMakeLists
files with pytest.

The staged tree goes first on PYTHONPATH, so the tests exercise the working
tree, not the code already installed in the image.
"""
import os
import re
import shutil
import subprocess
import sys

from visionport.vpros.scripts.rospy_to_vpros import rospy_to_vpros

SRC = "/src"            # repo, read-only
WORK = "/work"          # writable staging area
INSTALL = os.path.join(WORK, "install")
TESTS = os.path.join(WORK, "tests")

# Directories under a package that ship next to the python module in the
# install space (the image build copies the whole package dir).
RESOURCE_DIRS = ("config", "webapps", "launch")

CONFTEST = '''\
"""Generated by scripts/test_local_run.py -- do not edit in the staging tree.

vpros refuses get_param/Publisher calls until a node exists, the same way ROS
needs a master. The suite gets one node for the whole session, pointed at the
throwaway broker that scripts/test_local.sh starts.
"""
import visionport.vpros as rospy

rospy.init_node("lg_ros_nodes_offline_tests")
'''


def log(msg):
    print(msg, flush=True)


def stage_packages():
    """Mirror the image's install-space layout into INSTALL, transpiled."""
    staged = []
    for pkg in sorted(os.listdir(SRC)):
        pkg_dir = os.path.join(SRC, pkg)
        module_dir = os.path.join(pkg_dir, "src", pkg)
        if not os.path.isdir(module_dir):
            # message-definition and non-python packages have no module tree;
            # their generated python lives in visionport.vpros.models.
            continue
        dest = os.path.join(INSTALL, pkg)
        shutil.copytree(module_dir, dest)
        for extra in ("scripts",) + RESOURCE_DIRS:
            extra_src = os.path.join(pkg_dir, extra)
            if os.path.isdir(extra_src):
                shutil.copytree(extra_src, os.path.join(dest, extra),
                                dirs_exist_ok=True)
        staged.append(pkg)
    return staged


def stage_tests(test_files):
    """Copy each package's test dir, preserving repo-relative paths."""
    for rel in test_files:
        pkg = rel.split("/")[0]
        test_src = os.path.join(SRC, pkg, "test")
        test_dest = os.path.join(TESTS, pkg, "test")
        if os.path.isdir(test_src) and not os.path.exists(test_dest):
            shutil.copytree(test_src, test_dest)


def transpile_tree(root):
    """Rewrite every python file under root to the vpros dialect."""
    count = 0
    for dirpath, _dirnames, filenames in os.walk(root):
        for name in filenames:
            if not name.endswith(".py"):
                continue
            path = os.path.join(dirpath, name)
            try:
                with open(path) as handle:
                    original = handle.read()
            except (OSError, UnicodeDecodeError):
                continue
            converted = rospy_to_vpros(original)
            if converted != original:
                with open(path, "w") as handle:
                    handle.write(converted)
                count += 1
    return count


def registered_tests():
    """The nosetests each package registers in its CMakeLists.txt.

    Same source of truth as scripts/test_runner.py, so this suite and CI agree
    on what the offline tests are.
    """
    found = []
    for pkg in sorted(os.listdir(SRC)):
        cmake = os.path.join(SRC, pkg, "CMakeLists.txt")
        if not os.path.isfile(cmake):
            continue
        with open(cmake) as handle:
            for line in handle:
                match = re.search(r"^[^#]*catkin_add_nosetests\((.*)\)", line)
                if match:
                    found.append("%s/%s" % (pkg, match.group(1).strip()))
    return found


def run(test_files, pytest_args):
    """Run the whole suite in one pytest process.

    A process per module cost more in interpreter startup and broker handshake
    than the tests themselves took. Module basenames are unique across the
    packages, so one rootdir collects them all without import collisions.
    """
    present, missing = [], []
    for rel in test_files:
        (present if os.path.isfile(os.path.join(TESTS, rel)) else missing).append(rel)

    argv = [sys.executable, "-m", "pytest", "-q", "--no-header"]
    argv += present + pytest_args
    proc = subprocess.Popen(argv, cwd=TESTS, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True)
    output = []
    for line in proc.stdout:
        sys.stdout.write(line)
        output.append(line)
    sys.stdout.flush()
    code = proc.wait()

    # pytest names the offending file in every FAILED/ERROR summary line, so a
    # module is bad if it shows up there, or if the run died without saying
    # which module did it.
    blamed = set()
    for line in output:
        match = re.match(r"^(?:FAILED|ERROR)\s+(\S+?)(?:::|\s|$)", line)
        if match:
            blamed.add(match.group(1))

    results = {rel: None for rel in missing}
    for rel in present:
        if rel in blamed:
            results[rel] = "failed"
        elif code and not blamed:
            results[rel] = "suite failed (exit %d)" % code
        else:
            results[rel] = "ok"
    return results, code


def main():
    pytest_args = sys.argv[1:]
    os.makedirs(INSTALL, exist_ok=True)
    os.makedirs(TESTS, exist_ok=True)

    staged = stage_packages()
    log("staged %d packages into the install-space mirror" % len(staged))

    test_files = registered_tests()
    log("found %d registered nosetests" % len(test_files))
    stage_tests(test_files)

    log("transpiled %d modules" % (transpile_tree(INSTALL) + transpile_tree(TESTS)))

    with open(os.path.join(TESTS, "conftest.py"), "w") as handle:
        handle.write(CONFTEST)

    # Working tree first, then whatever the image already has installed
    # (appctl_support, visionport itself, third-party wheels).
    os.environ["PYTHONPATH"] = ":".join(
        [INSTALL] + [p for p in [os.environ.get("PYTHONPATH")] if p]
    )

    results, code = run(test_files, pytest_args)

    bad = sorted(k for k, v in results.items() if v != "ok")
    log("\n=== SUMMARY ===")
    for rel in sorted(results):
        log("%-52s %s" % (rel, results[rel] or "MISSING in staging tree"))
    log("%d/%d test modules passed" % (len(results) - len(bad), len(results)))
    return 1 if (bad or code) else 0


if __name__ == "__main__":
    sys.exit(main())
