<?xml version="1.0"?>
<theme name="Blackboard" format="1.1">
    <color_scheme>Charcoal</color_scheme>
    <key_style>gradient</key_style>
    <roundrect_radius>3.0</roundrect_radius>
    <key_size>90.0</key_size>
    <key_fill_gradient>8.0</key_fill_gradient>
    <key_stroke_gradient>0.0</key_stroke_gradient>
    <key_gradient_direction>-3.0</key_gradient_direction>
    <key_label_font></key_label_font>
    <key_label_overrides/>
</theme>
